# Exploring Data: An Introduction to Pandas and DataFrames

**Pandas** is the essential Python library for data analysis. Its main structure, the **DataFrame**, is like a smart, programmable spreadsheet — Excel or Google Sheets with the full power of Python behind it.

In this notebook we'll load a real dataset into a DataFrame and run the "health check" every data scientist does first: getting to know your data before you analyze it.

## How to Use This Notebook

You've just watched your instructor demonstrate today's key ideas — now it's your turn to work through the notebook with your partner, at your own pace.

**Start here:** get your data loaded. Fill in and run the import and data-loading cells near the top.

As you go:
- Cells flagged as demos are ones you'll **recreate yourself** — that's how the ideas stick.
- Wherever you see `# YOUR CODE HERE`, it's your turn to write the code.
- Check `*Hint:*` notes when you and your partner get stuck, and the **Reference Card** at the end.

## Teaching Notes: 10-Minute Launch

*(Notes for you, the instructor. Students never see this notebook.)*

**Set up two screens.** Put the **student notebook** on the projector, and keep **this instructor notebook open on a second device** (a second laptop, a tablet, a printout, or a second monitor) as your private reference. This notebook shows the **completed code** for every demo cell. **You don't need to memorize anything** — read the line here and type it into the projected student notebook.

**The notebook is now in two parts.** Everything above the 🚀 **Your Turn** divider is the demo you lead; everything below it is what pairs do on their own. The demo cells run together before that divider, so you can work straight down without jumping around.

**During the demo (~10 minutes):** type these cells live into the projected student notebook, talking through your thinking as you go:

1. `import pandas as pd` — we load a *library* of tools; `pd` is the standard nickname.
2. `pd.read_csv(...)` — pull a real dataset (Berkeley Earth global temperatures) from the web into a DataFrame.
3. `global_temps.head()` — the "health check." Note that `.head()`, `.tail()`, `.shape`, `.info()`, and `.describe()` all follow the **same `dataframe.method()` pattern**, so students can do the other four on their own after the hand-off.
4. `.columns` then **rename** — the raw column names are confusing; assign the clean list so `ave_temp` exists for the filter. Type the list **exactly**.
5. Boolean filter **Step 1** (`hot_cities = global_temps['ave_temp'] >= 35`) — a condition makes a column of `True`/`False`.
6. Boolean filter **Step 3** (`high_temps = global_temps[hot_cities]`) — feed that condition back in to keep only matching rows. This is the key move; the rest of the notebook is variations on it.

**Tip:** do a quick run-through on your own before class — it makes the live typing feel easy.

**Then release the class at the 🚀 Your Turn divider.** Pairs first *finish the first look* (`.tail()`, `.shape`, `.info()`, `.describe()` — same pattern) and then continue on their own through selecting columns, combining conditions, `loc`/`iloc`, values, and `groupby`.

**As you circulate:**
- Use the **Think About It** prompts (after `.describe()` and after `groupby`) to push from mechanical coding into interpretation.
- Point fast finishers to the **Challenge** section.
- This notebook has the worked solutions for every practice cell (the `###` markers) — your answer key while helping.
- Reconvene after pairs have grouped by country to discuss what the averages do and don't reveal.

## Data Structures (cont.)

We have already seen a couple examples of **structured data**: lists and dictionaries.

### Lists

Lists are **ordered**, meaning the items are labeled using an **index**. 

*Hint: list items are numbered starting at 0, so `grocery_list[0]` is the first item.*

In [1]:
grocery_list = ["eggs", "milk", "juice"]   

# Print "milk"
###
grocery_list[1]
###

'milk'

### Arrays

Arrays are a special type of list that contains only one data type. This homogeneity allows for more efficient memory usage and faster numerical computations, making them a favorite in scientific computing. Arrays are typically more rigid than lists.

In [2]:
# Which list is an array?
planet_list = ['mercury', 'venus', 'earth', 'mars', 'jupiter']
age_list = [3, 8, 12.0, 38, 40]
number_list = [4, 'five', 'ten', 32]

The key takeaway for both lists and arrays is their integer-based indexing. You retrieve an element by its numerical position, starting from zero.

## The Tabular Powerhouse: DataFrames
Enter the dataframe, a structure that brings together the concepts of lists, arrays, and dictionaries to create a powerful tool for data analysis. A dataframe is a two-dimensional data structure with labeled rows and columns. Imagine a spreadsheet, and you have a good mental model of a dataframe.

## Importing the Pandas Library

To use a library's functions, we **import** it. It's common to give it a short nickname so we don't type the full name every time: `import <library_name> as <abbreviation>`. Almost everyone imports pandas as `pd`.

**Your instructor works through this one with the class. When you work on your own, you'll write it here yourself.**

In [ ]:
# Import the pandas library and give it the nickname pd
###
import pandas as pd
###

A Pandas dataframe should look familiar. It is how data is structured in spreadsheets like Excel and Google Sheets. The bold numbers on the left are known as the **index** and allow us to number rows. The column names allow us to label and reference individual arrays in the dataframe.

## Reading Data into a DataFrame from a .csv File

Usually we load data from an existing file, or **dataset**. The most common format is a `.csv` ("comma separated values") file, which we read with `pd.read_csv()`. The string inside the parentheses is the **file path** — the directions to the file (see "Supplementary Information" for more).

We'll use an authentic dataset of historical global temperatures from [Berkeley Earth](https://berkeleyearth.org/about/):

https://raw.githubusercontent.com/jdomyancich/big-data-camp/refs/heads/main/data/global_temps.csv

**Your instructor works through this one with the class. When you work on your own, you'll write it here yourself.**

In [ ]:
# Read the file above into a dataframe named global_temps
###
global_temps = pd.read_csv("https://raw.githubusercontent.com/jdomyancich/big-data-camp/refs/heads/main/data/global_temps.csv")
###

### Getting a First Look

Once your data is loaded, get a feel for it: its structure, size, and any issues like missing values. Below are the essential methods and attributes for that first inspection.

*(Reminder: a DataFrame is an **object**. A **method** does something and uses parentheses, like `.head()`; an **attribute** is a stored property with no parentheses, like `.shape`.)*

#### `.head()` - View the first few rows

Shows the first 5 rows by default — a quick way to confirm the data loaded correctly and see the column names.

**Your instructor works through this one with the class. When you work on your own, you'll write it here yourself.**

In [ ]:
# Print the first few rows
###
global_temps.head()
###

# Data Wrangling

This is one of the hardest parts of working with data. Raw data is rarely ready to be analyzed. Scientists spend a lot of time manipulating their data to get it into a form that can be used. We call it "wrangling".

<img src = 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Cats_in_aoshima_island_1.JPG/1600px-Cats_in_aoshima_island_1.JPG' width = 400>

Possible problems with data:
* Getting only the data you need 
* Incorrect data types
* Incorrect units

## Working with Columns

You can think of the data frame from two perspectives: columns and rows. Columns are much easier to work with because they are arrays, meaning all the elements in a column are the same datatype (or they should be).

#### `.columns` - View column names

This attribute returns a list of all the column names in your dataframe.

*Hint: `.columns` is an attribute, so no parentheses.*

In [ ]:
# View the column names
###
global_temps.columns
###

Sometimes the original column names are confusing. You can change them by setting a list of new column names to `data.columns`

*Hint: assign this exact list so the rest of the notebook keeps working:*
`['date', 'ave_temp', 'ave_temp_uncer', 'city', 'country', 'latitude', 'longitude']`

In [ ]:
# Rename the columns using the list of new names above
###
global_temps.columns = ['date', 'ave_temp', 'ave_temp_uncer', 'city', 'country', 'latitude', 'longitude']
###
global_temps.head()

## Conditional Filtering (Boolean Indexing)

This is one of the most powerful features of Pandas: selecting rows based on whether they meet a certain condition. You pass a Series of `True`/`False` values (a "Boolean Series") inside the square brackets. Only rows where the value is `True` will be returned. The easiest way to undrstand this is by breaking it down, step by step:

**Step 1: Create a condition**

Let's ask a question: "Which cities have experienced very hot average temperature for a specific month?" Let's say 35&deg;C (95&deg;F) is "very hot".

**Your instructor works through this one with the class. When you work on your own, you'll write it here yourself.**

In [ ]:
# Create a condition for ave_temp of 35 or higher; store it in hot_cities
###
hot_cities = global_temps['ave_temp'] >= 35
###

**Step 2: Generate the Boolean Series**

If you `print(hot_cities)`, you wouldn't see the cities. You would see the Boolean Series—the `True`/`False` answer for every single city:

In [15]:
print(hot_cities)

0         False
1         False
2         False
3         False
4         False
          ...
239172    False
239173    False
239174    False
239175    False
239176    False
Name: ave_temp, Length: 239177, dtype: bool

**Step 3: Use the Boolean Series to filter the dataframe**
Now, you use that condition (the Boolean Series) as a filter inside the square brackets of your original dataframe.

Pandas will look at your `global_temps` dataframe, and for every row, it will check the corresponding value in your condition series. It will only keep the rows where the value is True.

**Your instructor works through this one with the class. When you work on your own, you'll write it here yourself.**

In [ ]:
# Use hot_cities to filter global_temps; store the result in high_temps
###
high_temps = global_temps[hot_cities]
###
high_temps.head()

---

## 🚀 Your Turn

You've recreated the demo cells above with your partner. Keep going on your own from here: first *finish the first look* — `.tail()`, `.shape`, `.info()`, and `.describe()` all work just like `.head()` — then work down through selecting columns, filtering rows, `loc`/`iloc`, and `groupby`.

#### `.tail()` - View the last few rows

Like `.head()`, but shows the last 5 rows — handy for spotting stray summary or blank rows at the end of a file.

*Hint: this works just like the `.head()` Example above — call `.tail()` on `global_temps`.*

In [ ]:
# Show the last few rows
###
global_temps.tail()
###

#### `.shape` - Check the dimensions

An attribute (no parentheses) that returns `(number_of_rows, number_of_columns)` — how big your dataset is.

*Hint: same idea as `.head()`, but `.shape` is an attribute, so it takes no parentheses.*

In [ ]:
# Check the dimensions (number of rows and columns)
###
global_temps.shape
###

#### `.info()` - Get a technical summary

A concise technical summary: the number of columns, each column's data type (`int64`, `float64`, `object` — often strings), how many non-null values it has, and memory usage.

*Hint: same `global_temps.method()` pattern as the `.head()` Example.*

In [ ]:
# Print a technical summary of the dataframe
###
global_temps.info()
###

#### `.describe()` - Generate descriptive statistics

Summary statistics (count, mean, min, max, quartiles) for the numerical columns — a quick way to see the spread of your data and spot possible outliers.

*Hint: same `global_temps.method()` pattern as the `.head()` Example.*

In [ ]:
# Show descriptive statistics for the number columns
###
global_temps.describe()
###

#### Think About It

Look at the statistics `.describe()` produced for the temperature columns:

1. What do the **min** and **max** values tell you about the range of climates captured in this dataset?
2. How close is the **mean** to the **median** (the 50% row)? What might that suggest about the distribution?
3. Does any number surprise you? Write down one question the summary raises that you could investigate later.

### Selecting Columns

The most common way to get data from a DataFrame is by selecting one or more columns. Remember, each column is an array, meaning all the elements in a column are the same datatype (or they should be).

#### Selecting a Single Column
To select a single column, use square bracket notation with the column name as a string:

*Hint: put the column name as a string inside square brackets, like `global_temps['column_name']`.*

In [12]:
# Select the city column
###
global_temps['city']
###

0         Abidjan
1         Abidjan
2         Abidjan
3         Abidjan
4         Abidjan
           ...
239172       Xian
239173       Xian
239174       Xian
239175       Xian
239176       Xian
Name: city, Length: 239177, dtype: object

#### Selecting Multiple Columns

To select multiple columns, you need to pass a **list** of column names inside the square brackets. This will return a new dataframe.

*Hint: pass a **list** inside the brackets, like `global_temps[['col1', 'col2']]`. Store the result in `selected_columns` so the next line works.*

In [ ]:
# Select date, ave_temp, and city into a dataframe named selected_columns
###
columns = ["date", "ave_temp", "city"]
selected_columns = global_temps[columns]
###
selected_columns.head()

### Combining Conditions

You can combine multiple conditions using logical operators:

- & for AND (both conditions must be true)
- | for OR (at least one condition must be true)

Remember to put each condition in parentheses!

`(first_condition) & (second_condition)`

*Hint: store your combined condition in a variable called `condition`, then use it to filter `global_temps` (the next cell already does the filtering for you).*

In [ ]:
# Combine two conditions with & and store them in condition
###
condition = (global_temps['country'] == 'India') & (global_temps['ave_temp'] > 36)
###
hot_india = global_temps[condition]
hot_india

### What about rows?

Rows are a little trickier to reference because they are not arrays. In columns, we can reference the name of the columns that we are interested in. Also, the elements in a column are the same data type. Since rows contain the elements of several different arrays, they can contain multiple data types and require a different way of thinking. We can filter rows two ways: by index or by label.

For the `iloc` method, you can pass a number `[5]`, range of numbers `[5:9]`, list `[23, 45, 87]`. These values correspond to the bold index values in the first column.

`iloc`

In [18]:
# pass a value
hot_india.iloc[5]

date              2010-05-01
ave_temp              36.477
ave_temp_uncer         0.318
city                  Jaipur
country                India
latitude              26.52N
longitude             75.22E
Name: 99195, dtype: object

In [19]:
# pass a range
hot_india.iloc[3:6]

             date  ave_temp  ave_temp_uncer    city country latitude longitude
98931  1988-05-01    36.076           0.418  Jaipur   India   26.52N    75.22E
99016  1995-06-01    36.031           0.229  Jaipur   India   26.52N    75.22E
99195  2010-05-01    36.477           0.318  Jaipur   India   26.52N    75.22E

In [20]:
# pass a list
hot_india.iloc[[1, 3, 5]]

             date  ave_temp  ave_temp_uncer    city country latitude longitude
65546  1995-06-01    36.291           0.338   Delhi   India   28.13N    77.27E
98931  1988-05-01    36.076           0.418  Jaipur   India   26.52N    75.22E
99195  2010-05-01    36.477           0.318  Jaipur   India   26.52N    75.22E

`loc`

The `loc` method allows you to search for labels within the columns. You can use values, booleans, and conditionals.

*Hint: build a condition first (like in the Boolean filter Example), then pass it to `global_temps.loc[...]`.*

In [ ]:
# Use .loc with a single condition to select rows
###
condition = global_temps['city'] == 'Chicago'
chicago = global_temps.loc[condition]
chicago.head()
###

In [ ]:
# Use .loc with two conditions combined
###
conditions = (global_temps['city'] == 'Chicago') & (global_temps['ave_temp'] > 25)
global_temps.loc[conditions]
global_temps.head()
###

### Working with Values

The temperatures for all the cities are in Celsius. Let's convert them to Fahrenheit so they are easier to understand.

$$ T(F) = \frac{9}{5}T(C)+32 $$

**Define a function for converting Celsius to Fahrenheit.**

*Hint: use the formula above. Start with `def C_to_F(temp_C):`, compute `(temp_C * 9/5) + 32`, and `return` the result.*

In [ ]:
# Define a function named C_to_F that converts Celsius to Fahrenheit
###
def C_to_F(temp_C):
    temp_F = (temp_C * 9/5) + 32
    return temp_F
###

**"Apply" the function to the data.**

In [24]:
global_temps['ave_temp_F'] = global_temps['ave_temp'].apply(C_to_F)
global_temps.head()

,date,ave_temp,ave_temp_uncer,city,country,latitude,longitude,ave_temp_F
0,1849-01-01,26.704,1.435,Abidjan,Côte D'Ivoire,5.63N,3.23W,80.0672
1,1849-02-01,27.434,1.362,Abidjan,Côte D'Ivoire,5.63N,3.23W,81.3812
2,1849-03-01,28.101,1.612,Abidjan,Côte D'Ivoire,5.63N,3.23W,82.5818
3,1849-04-01,26.140,1.387,Abidjan,Côte D'Ivoire,5.63N,3.23W,79.0520
4,1849-05-01,25.427,1.200,Abidjan,Côte D'Ivoire,5.63N,3.23W,77.7686

# Data Analysis

With clean data in hand, we can start to summarize it and draw conclusions. One of the most useful tools for that is grouping.

## Grouping with `groupby()`

`groupby()` lets you split your data into groups, apply a function to each group, and combine the results — the "split-apply-combine" strategy, one of the most-used tools in Pandas.

### How it Works (The "Split-Apply-Combine" Strategy):

1. **Split** the data into groups that share the same value for the grouping key.
2. **Apply** an aggregation function to each group — `mean()`, `sum()`, `count()`, `max()`, `min()`, etc.
3. **Combine** the results back into one series or dataframe, with the grouping keys as the index.

All in a single line:

`df.groupby('split_group')[data_to_be_applied].function_applied_to_data`

For example, we can group the cities by country and then calculate the average temperature for each country:

*Hint: follow the template above — `global_temps.groupby('country')['ave_temp'].mean()` — and store it in `country_data`.*

In [ ]:
# Group by country and take the mean of ave_temp; store it in country_data
###
country_data = global_temps.groupby('country')['ave_temp'].mean()
###
country_data.head()

#### Think About It

You just calculated the average temperature for each country.

1. Which countries show up as the **hottest**? Which look the **coldest**?
2. How do these results fit with what you know about each country's **geography** (latitude, elevation, distance from the ocean)?
3. This average combines *every month of every year* for each country. What might that hide? What would you want to check before trusting it?

## Challenge: Explore on Your Own

Finished early? Put your new skills together on questions you actually care about. Use as many of the cells below as you need, and ask another pair or the instructor if you get stuck.

1. **Zoom in.** Filter the data to a country or city you're curious about and take a look.
2. **Find the extreme.** Use `groupby` together with `.sort_values()` to find the country with the highest average temperature.
3. **Make something new.** Create a new column (for example, temperature in &deg;F using the `C_to_F` function) and then filter the data using your new column.

In [ ]:
# Challenge 1: Zoom in on a country or city you're curious about
###
india = global_temps[global_temps['country'] == 'India']
india.head()
###

In [ ]:
# Challenge 2: Which country has the highest average temperature?
###
global_temps.groupby('country')['ave_temp'].mean().sort_values(ascending=False).head()
###

In [ ]:
# Challenge 3: Create a new column, then filter on it
###
global_temps['ave_temp_F'] = global_temps['ave_temp'].apply(C_to_F)
global_temps[global_temps['ave_temp_F'] > 95].head()
###

## Reference Card

Stuck? Here are the key patterns from today, all in one place.

**Load a dataset from a file path:**
`global_temps = pd.read_csv('https://raw.githubusercontent.com/jdomyancich/big-data-camp/refs/heads/main/data/global_temps.csv')`

**Inspect a DataFrame** — all use the same `dataframe.method()` pattern:
`global_temps.head()` · `global_temps.tail()` · `global_temps.info()` · `global_temps.describe()`
`global_temps.shape` and `global_temps.columns` are *attributes* — no parentheses.

**Rename the columns:**
`global_temps.columns = ['date', 'ave_temp', 'ave_temp_uncer', 'city', 'country', 'latitude', 'longitude']`

**Select columns:**
- One column: `global_temps['city']`
- Several columns: `global_temps[['date', 'ave_temp', 'city']]`

**Filter rows by a condition (Boolean indexing):**
`condition = global_temps['ave_temp'] >= 35`
`hot = global_temps[condition]`
Combine conditions with `&` (and) or `|` (or), each in parentheses:
`global_temps[(global_temps['country'] == 'India') & (global_temps['ave_temp'] > 36)]`

**Apply a function to a column:**
`global_temps['ave_temp_F'] = global_temps['ave_temp'].apply(C_to_F)`

**Group and summarize (split-apply-combine):**
`global_temps.groupby('country')['ave_temp'].mean()`